deployment = "deployment.toml"

# capsule version
version = "0.4.1 "

[[contracts]]
name = "ckb-dex-contract"
template_type = "Rust"

[[contracts]]
name = "liquidity-poll-contract"
template_type = "Rust"
